[package]
name = "fast_thumbhash"
version = "0.1.0"
edition = "2021"

[lib]
name = "fast_thumbhash"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
thumbhash = "0.1"
